# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UhshZLQjKYEgGzWTdXuH7CsLl05SdGRC
"""

!pip3 install minio

from minio import Minio
from minio.error import S3Error

def main():
    # Create a client with the MinIO server playground, its access key
    # and secret key.

    client = Minio(
        "s3.csc.uvic.ca:9000",
        access_key="K",
        secret_key="",
    )

    buckets = client.list_buckets()
    for bucket in buckets:
      print(bucket.name, bucket.creation_date)

    # # Make 'RawDataStorage' bucket if not exist.
    # found = client.bucket_exists("RawDataStorage")
    # if not found:
    #     client.make_bucket("RawDataStorage")
    # else:
    #     print("Bucket 'RawDataStorage' already exists")

    # # Upload '/content/example.json' as object name
    # # 'example.json' to bucket 'asiatrip'.
    # client.fput_object(
    #     "RawDataStorage", "example.json", "/content/example.json",
    # )
    # print(
    #     "'/content/example.json' is successfully uploaded as "
    #     "object 'example.json' to bucket 'RawDataStorage'."
    # )

if __name__ == "__main__":
    try:
        main()
    except S3Error as exc:
        print("error occurred.", exc)